spring:
  datasource:
    url: jdbc:h2:mem:planets
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
  h2:
    console:
      enabled: true

     


